import asyncio
import os
import shutil
import tempfile
import logging
from typing import Dict, Any
from app.deps import Deps

logger = logging.getLogger(__name__)

class DeployAgentClient:
    def __init__(self, deps: Deps):
        self.deps = deps

    async def deploy(self, repo_url: str, branch: str, service_name: str) -> str:
        """
        Deploy the specified branch of the repo to Cloud Run using gcloud.
        """
        # Create a temporary directory
        temp_dir = tempfile.mkdtemp()
        try:
            # 1. Clone the repository at the specific branch
            token = self.deps.scm.get_access_token()
            
            auth_url = repo_url.replace("https://", f"https://x-access-token:{token}@")
            clone_cmd = f"git clone --branch {branch} --single-branch {auth_url} {temp_dir}"
            logger.info(f"Cloning repo (URL masked)")
            proc = await asyncio.create_subprocess_shell(
                clone_cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await proc.communicate()
            if proc.returncode != 0:
                raise Exception(f"Git clone failed: {stderr.decode()}")

            import pathlib
            project_id = self.deps.settings.google_cloud_project
            package_json_paths = sorted(list(pathlib.Path(temp_dir).rglob("package.json")), key=lambda p: len(p.parts))
            source_dir = str(package_json_paths[0].parent) if package_json_paths else temp_dir
            logger.info(f"Auto-detected source directory: {source_dir}")

            # Hack: Next.js/Docker generated by create-next-app uses `npm ci` which crashes if lockfiles are out of sync.
            # Replace npm ci with npm install in Dockerfile.
            dockerfile_path = os.path.join(source_dir, "Dockerfile")
            if os.path.exists(dockerfile_path):
                with open(dockerfile_path, "r") as f:
                    df_content = f.read()
                df_content = df_content.replace("npm ci", "npm install")
                with open(dockerfile_path, "w") as f:
                    f.write(df_content)

            # Use real Firebase credentials so preview environments can test data saving
            firebase_project_id = "YOUR_PROJECT_ID"
            firebase_api_key = "REDACTED_FIREBASE_API_KEY"
            firebase_auth_domain = "YOUR_PROJECT_ID.firebaseapp.com"
            
            env_vars = f"NEXT_PUBLIC_FIREBASE_PROJECT_ID={firebase_project_id},NEXT_PUBLIC_FIREBASE_API_KEY={firebase_api_key},NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN={firebase_auth_domain}"

            deploy_cmd = (
                f"gcloud run deploy {service_name} "
                f"--source {source_dir} "
                f"--region asia-northeast1 "
                f"--project {project_id} "
                f"--allow-unauthenticated "
                f"--set-env-vars {env_vars} "
                f"--set-build-env-vars {env_vars} "
                f"--quiet --format='value(status.url)'"
            )
            logger.info(f"Deploying to Cloud Run: {deploy_cmd}")
            proc = await asyncio.create_subprocess_shell(
                deploy_cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await proc.communicate()
            if proc.returncode != 0:
                raise Exception(f"gcloud run deploy failed: {stderr.decode()}")

            url = stdout.decode().strip()
            return url
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)
